services:

  mysql:

    image: mariadb:10.11

    container_name: filmoteka_mysql

    restart: unless-stopped

    environment:

      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MARIADB_DATABASE: ${MYSQL_DATABASE}

      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}

      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_general_ci

    volumes:

      - mysql_data:/var/lib/mysql

      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

    healthcheck:

      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 20s

      timeout: 10s

      retries: 5

      start_period: 40s

    networks:
      - filmoteka_net

    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

      args:
        BUILDKIT_INLINE_CACHE: 0

    container_name: filmoteka_backend
    restart: unless-stopped

    environment:

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      APP_ENV: production

    volumes:
      - ./uploads:/var/www/filmoteka/uploads

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - filmoteka_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: filmoteka_nginx
    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - ./uploads:/var/www/filmoteka/uploads

    depends_on:
      - backend

    networks:
      - filmoteka_net

volumes:

  mysql_data:
    driver: local

networks:

  filmoteka_net:
    driver: bridge
